const cups = [
  {
    id: 23,
    name: `The Ace of Cups`,
    rank: 1,
    description: `Cups`,
    revDescription: `Cups`,
    keywords: [`Cups`],
  },
  {
    id: 24,
    name: `The Two of Cups`,
    rank: 2,
    description: `Cups`,
    revDescription: `Cups`,
    keywords: [`Cups`],
  },
  {
    id: 25,
    name: `The Three of Cups`,
    rank: 3,
    description: `Cups`,
    revDescription: `Cups`,
    keywords: [`Cups`],
  },
  {
    id: 26,
    name: `The Four of Cups`,
    rank: 4,
    description: `Cups`,
    revDescription: `Cups`,
    keywords: [`Cups`],
  },
  {
    id: 27,
    name: `The Five of Cups`,
    rank: 5,
    description: `Cups`,
    revDescription: `Cups`,
    keywords: [`Cups`],
  },
  {
    id: 28,
    name: `The Six of Cups`,
    rank: 6,
    description: `Cups`,
    revDescription: `Cups`,
    keywords: [`Cups`],
  },
  {
    id: 29,
    name: `The Seven of Cups`,
    rank: 7,
    description: `Cups`,
    revDescription: `Cups`,
    keywords: [`Cups`],
  },
  {
    id: 30,
    name: `The Eight of Cups`,
    rank: 8,
    description: `Cups`,
    revDescription: `Cups`,
    keywords: [`Cups`],
  },
  {
    id: 31,
    name: `The Nine of Cups`,
    rank: 9,
    description: `Cups`,
    revDescription: `Cups`,
    keywords: [`Cups`],
  },
  {
    id: 32,
    name: `The Ten of Cups`,
    rank: 10,
    description: `Cups`,
    revDescription: `Cups`,
    keywords: [`Cups`],
  },
]

export default cups.map(card => new Object({...card, suit: "Cups"}))
