const pentacles = [
  {
    id: 37,
    name: `The Ace of Pentacles`,
    rank: 1,
    description: `The Ace represents potential in every suit and it's no different in Pentacles. It might be the first steps towards a business venture or the beginnings of a new family. Whatever we plant now will someday blossom into something glorious.`,
    revDescription: `Pentacles`,
    keywords: [`Potent`, `Wealthy`, `Grounded`],
  },
  {
    id: 38,
    name: `The Two of Pentacles`,
    rank: 2,
    description: `Change can be uncomfortable, a new job, a change at work, something new at home, all of these things can topple us off balance. This card reminds us the very act of holding balance can be fun or informative, the challenge itself is why we're alive. Let's embrace the change rather than letting it knock us over.`,
    revDescription: `Pentacles`,
    keywords: [`Dynamic`],
  },
  {
    id: 39,
    name: `The Three of Pentacles`,
    rank: 3,
    description: `We love to see our hard work pay off. This card reminds us that good things will happen if we dedicate ourselves and persevere through the difficulties.`,
    revDescription: `Pentacles`,
    keywords: [`Unified`, `Determined`, `Disciplined`],
  },
  {
    id: 40,
    name: `The Four of Pentacles`,
    rank: 4,
    description: `On the surface this card promises wealth. Beneath that attractive veneer lies the truth: it's important to find stability, but dangerous to hunt for it among the material. Sometimes it's better to give away what we don't need and provide for others.`,
    revDescription: `Pentacles`,
    keywords: [`Wealthy`,`Stable`,`Miserly`],
  },
  {
    id: 41,
    name: `The Five of Pentacles`,
    rank: 5,
    description: `This card represents a hard time brought on by loss. It might be the loss of a job or some other instability. These things bring anxiety and worry and for good reason: through all of all of these trials, we'll generally only have ourselves to rely on. We should quiet our doubts and prepare to do what we must.`,
    revDescription: `Pentacles`,
    keywords: [`Anxious`, `Lost`, `Self-Sufficient`],
  },
  {
    id: 42,
    name: `The Six of Pentacles`,
    rank: 6,
    description: `Someone's hard work has paid off and now it's time to enjoy the spoils! If it's your own, be charitable with them. Give credit where credit is due and share what you can. Other people will do the same for you.`,
    revDescription: `Pentacles`,
    keywords: [`Charitable`, `Prosperous`],
  },
  {
    id: 43,
    name: `The Seven of Pentacles`,
    rank: 7,
    description: `Let's take a step back. Look at everything that's come to pass and figure out the future. We've put in a lot of time and effort, have they worked out for us? Sometimes we don't get what we expected, are there hidden rewards for the things that we want?`,
    revDescription: `Pentacles`,
    keywords: [`Assessing`],
  },
  {
    id: 44,
    name: `The Eight of Pentacles`,
    rank: 8,
    description: `We all work towards some kind of mastery, and this card is the representation of that. At this point we're verging on the edge of it. It might take tremendous effort but we have everything we need to become a true craftsperson.`,
    revDescription: `Pentacles`,
    keywords: [`Masterful`],
  },
  {
    id: 45,
    name: `The Nine of Pentacles`,
    rank: 9,
    description: `After all those long hours it's time to enjoy the fruits of our labor. We can slow down, bask in things that used to be luxuries. This card tells us it's time to enjoy our reward.`,
    revDescription: `Pentacles`,
    keywords: [`Successful`, `Cultivated`],
  },
  {
    id: 46,
    name: `The Ten of Pentacles`,
    rank: 10,
    description: `We've made the journey and now we can stop to appreciate it. More importantly, we now have the chance to mentor other folks who struggle along the same path. This card asks us to share our wisdom so that others will someday join us.`,
    revDescription: `Pentacles`,
    keywords: [`Content`, `Instructive`],
  },
  {
    id: 47,
    name: `The Seer of Pentacles`,
    rank: 11,
    description: `The Seer represents a person or aspect of yourself that can be relied on. They're responsible and detail oriented but tend to shy away from the spotlight.`,
    revDescription: `Pentacles`,
    keywords: [`supportive`, `responsible`, `studious`],
  },
  {
    id: 48,
    name: `The Quester of Pentacles`,
    rank: 12,
    description: `The Quester represents a person or aspect of yourself that's utterly industrious. They don't need many friends, they rarely think about anything other than their work. While they're utterly loyal, they have a tendency to stubbornly stick with things even when they're a lost cause.`,
    revDescription: `Pentacles`,
    keywords: [`Industrious`, `Persistent`],
  },
  {
    id: 49,
    name: `The Sibyl of Pentacles`,
    rank: 13,
    description: `This Sibyl represents somebody or an aspect of yourself that trusts themself utterly. They know how to nurture and how to care. Often they're utterly dedicated to the people they consider their children.`,
    revDescription: `Pentacles`,
    keywords: [`Self-Possessed`, `Patient`, `Domestic`],
  },
  {
    id: 50,
    name: `The Sage of Pentacles`,
    rank: 14,
    description: `The Sage represents someone you know or an aspect of yourself who has nothing to prove. Utterly experienced and patient, the Sage might seem a little simple at first, but underneath their calm exterior lies someone with all the passion and skill to build anything they desire.`,
    revDescription: `Pentacles`,
    keywords: [`Satisfied`, `Patient`, `Practical`],
  },
]

export default pentacles.map(card => {return {...card, suit: "Pentacles"} })
