const pentacles = [
  {
    id: 37,
    name: `The Ace of Pentacles`,
    rank: 1,
    description: `Pentacles`,
    revDescription: `Pentacles`,
    keywords: [`Pentacles`],
  },
  {
    id: 38,
    name: `The Two of Pentacles`,
    rank: 2,
    description: `Pentacles`,
    revDescription: `Pentacles`,
    keywords: [`Pentacles`],
  },
  {
    id: 39,
    name: `The Three of Pentacles`,
    rank: 3,
    description: `Pentacles`,
    revDescription: `Pentacles`,
    keywords: [`Pentacles`],
  },
  {
    id: 40,
    name: `The Four of Pentacles`,
    rank: 4,
    description: `Pentacles`,
    revDescription: `Pentacles`,
    keywords: [`Pentacles`],
  },
  {
    id: 41,
    name: `The Five of Pentacles`,
    rank: 5,
    description: `Pentacles`,
    revDescription: `Pentacles`,
    keywords: [`Pentacles`],
  },
  {
    id: 42,
    name: `The Six of Pentacles`,
    rank: 6,
    description: `Pentacles`,
    revDescription: `Pentacles`,
    keywords: [`Pentacles`],
  },
  {
    id: 43,
    name: `The Seven of Pentacles`,
    rank: 7,
    description: `Pentacles`,
    revDescription: `Pentacles`,
    keywords: [`Pentacles`],
  },
  {
    id: 44,
    name: `The Eight of Pentacles`,
    rank: 8,
    description: `Pentacles`,
    revDescription: `Pentacles`,
    keywords: [`Pentacles`],
  },
  {
    id: 45,
    name: `The Nine of Pentacles`,
    rank: 9,
    description: `Pentacles`,
    revDescription: `Pentacles`,
    keywords: [`Pentacles`],
  },
  {
    id: 46,
    name: `The Ten of Pentacles`,
    rank: 10,
    description: `Pentacles`,
    revDescription: `Pentacles`,
    keywords: [`Pentacles`],
  },
]

export default pentacles.map(card => {return {...card, suit: "Pentacles"} })
