const pentacles = [
  {
    id: 1,
    name: `The Ace of Wands`,
    rank: 1,
    description: `Wands`,
    revDescription: `Wands`,
    keywords: [`Wands`],
  },
  {
    id: 2,
    name: `The Two of Wands`,
    rank: 2,
    description: `Wands`,
    revDescription: `Wands`,
    keywords: [`Wands`],
  },
  {
    id: 3,
    name: `The Three of Wands`,
    rank: 3,
    description: `Wands`,
    revDescription: `Wands`,
    keywords: [`Wands`],
  },
  {
    id: 4,
    name: `The Four of Wands`,
    rank: 4,
    description: `Wands`,
    revDescription: `Wands`,
    keywords: [`Wands`],
  },
  {
    id: 5,
    name: `The Five of Wands`,
    rank: 5,
    description: `Wands`,
    revDescription: `Wands`,
    keywords: [`Wands`],
  },
  {
    id: 6,
    name: `The Six of Wands`,
    rank: 6,
    description: `Wands`,
    revDescription: `Wands`,
    keywords: [`Wands`],
  },
  {
    id: 7,
    name: `The Seven of Wands`,
    rank: 7,
    description: `Wands`,
    revDescription: `Wands`,
    keywords: [`Wands`],
  },
  {
    id: 8,
    name: `The Eight of Wands`,
    rank: 8,
    description: `Wands`,
    revDescription: `Wands`,
    keywords: [`Wands`],
  },
  {
    id: 9,
    name: `The Nine of Wands`,
    rank: 9,
    description: `Wands`,
    revDescription: `Wands`,
    keywords: [`Wands`],
  },
  {
    id: 10,
    name: `The Ten of Wands`,
    rank: 10,
    description: `Wands`,
    revDescription: `Wands`,
    keywords: [`Wands`],
  },
]

export default pentacles.map(card => new Object({...card, suit: "Pentacles"}))
