const swords = [
  {
    id: 51,
    name: `The Ace of Swords`,
    rank: 1,
    description: `Swords`,
    revDescription: `Swords`,
    keywords: [`Swords`],
  },
  {
    id: 52,
    name: `The Two of Swords`,
    rank: 2,
    description: `Swords`,
    revDescription: `Swords`,
    keywords: [`Swords`],
  },
  {
    id: 53,
    name: `The Three of Swords`,
    rank: 3,
    description: `Swords`,
    revDescription: `Swords`,
    keywords: [`Swords`],
  },
  {
    id: 54,
    name: `The Four of Swords`,
    rank: 4,
    description: `Swords`,
    revDescription: `Swords`,
    keywords: [`Swords`],
  },
  {
    id: 55,
    name: `The Five of Swords`,
    rank: 5,
    description: `Swords`,
    revDescription: `Swords`,
    keywords: [`Swords`],
  },
  {
    id: 56,
    name: `The Six of Swords`,
    rank: 6,
    description: `Swords`,
    revDescription: `Swords`,
    keywords: [`Swords`],
  },
  {
    id: 57,
    name: `The Seven of Swords`,
    rank: 7,
    description: `Swords`,
    revDescription: `Swords`,
    keywords: [`Swords`],
  },
  {
    id: 58,
    name: `The Eight of Swords`,
    rank: 8,
    description: `Swords`,
    revDescription: `Swords`,
    keywords: [`Swords`],
  },
  {
    id: 59,
    name: `The Nine of Swords`,
    rank: 9,
    description: `Swords`,
    revDescription: `Swords`,
    keywords: [`Swords`],
  },
  {
    id: 60,
    name: `The Ten of Swords`,
    rank: 10,
    description: `Swords`,
    revDescription: `Swords`,
    keywords: [`Swords`],
  },
]

export default swords.map(card => {return {...card, suit: "Swords"} })
