const swords = [
  {
    id: 51,
    name: `The Ace of Swords`,
    rank: 1,
    description: `Like all the Aces the Ace of Swords signals potential. The suit of swords often represents intellect and the Ace tells us that we can use our intellect with judgement. It may be through a flash of insight or a series of judgements, but we have the power to begin a journey using nothing but our mind.`,
    revDescription: `Swords`,
    keywords: [`Truth`, `Clarity`],
  },
  {
    id: 52,
    name: `The Two of Swords`,
    rank: 2,
    description: `Some decisions feel like there's no chance for compromise. Opposing forces seem deadlocked in such a way there's no obvious path forward. This isn't a time for rash judgement. Let's take our time, weigh the different options and use our well-balanced position to find the best way forward.`,
    revDescription: `Swords`,
    keywords: [`Equilibrium`, `Stalemate`],
  },
  {
    id: 53,
    name: `The Three of Swords`,
    rank: 3,
    description: `Things don't always go well for us, and when they don't it's important to remember we shouldn't make rash decisions. Tragedy might demand quick action but it's usually better to wait until we've cleared our thoughts before we make any rash judgements.`,
    revDescription: `Swords`,
    keywords: [`Sorrow`, `Turmoil`, `Betrayal`],
  },
  {
    id: 54,
    name: `The Four of Swords`,
    rank: 4,
    description: `Swords`,
    revDescription: `Swords`,
    keywords: [`Swords`],
  },
  {
    id: 55,
    name: `The Five of Swords`,
    rank: 5,
    description: `Swords`,
    revDescription: `Swords`,
    keywords: [`Swords`],
  },
  {
    id: 56,
    name: `The Six of Swords`,
    rank: 6,
    description: `Swords`,
    revDescription: `Swords`,
    keywords: [`Swords`],
  },
  {
    id: 57,
    name: `The Seven of Swords`,
    rank: 7,
    description: `Swords`,
    revDescription: `Swords`,
    keywords: [`Swords`],
  },
  {
    id: 58,
    name: `The Eight of Swords`,
    rank: 8,
    description: `Swords`,
    revDescription: `Swords`,
    keywords: [`Swords`],
  },
  {
    id: 59,
    name: `The Nine of Swords`,
    rank: 9,
    description: `Swords`,
    revDescription: `Swords`,
    keywords: [`Swords`],
  },
  {
    id: 60,
    name: `The Ten of Swords`,
    rank: 10,
    description: `Swords`,
    revDescription: `Swords`,
    keywords: [`Swords`],
  },
]

export default swords.map(card => {return {...card, suit: "Swords"} })
