const wands = [
  {
    id: 65,
    name: `The Ace of Wands`,
    rank: 1,
    description: `Wands`,
    revDescription: `Wands`,
    keywords: [`Wands`],
  },
  {
    id: 66,
    name: `The Two of Wands`,
    rank: 2,
    description: `Wands`,
    revDescription: `Wands`,
    keywords: [`Wands`],
  },
  {
    id: 67,
    name: `The Three of Wands`,
    rank: 3,
    description: `Wands`,
    revDescription: `Wands`,
    keywords: [`Wands`],
  },
  {
    id: 68,
    name: `The Four of Wands`,
    rank: 4,
    description: `Wands`,
    revDescription: `Wands`,
    keywords: [`Wands`],
  },
  {
    id: 69,
    name: `The Five of Wands`,
    rank: 5,
    description: `Wands`,
    revDescription: `Wands`,
    keywords: [`Wands`],
  },
  {
    id: 70,
    name: `The Six of Wands`,
    rank: 6,
    description: `Wands`,
    revDescription: `Wands`,
    keywords: [`Wands`],
  },
  {
    id: 71,
    name: `The Seven of Wands`,
    rank: 7,
    description: `Wands`,
    revDescription: `Wands`,
    keywords: [`Wands`],
  },
  {
    id: 72,
    name: `The Eight of Wands`,
    rank: 8,
    description: `Wands`,
    revDescription: `Wands`,
    keywords: [`Wands`],
  },
  {
    id: 73,
    name: `The Nine of Wands`,
    rank: 9,
    description: `Wands`,
    revDescription: `Wands`,
    keywords: [`Wands`],
  },
  {
    id: 74,
    name: `The Ten of Wands`,
    rank: 10,
    description: `Wands`,
    revDescription: `Wands`,
    keywords: [`Wands`],
  },
]

export default wands.map(card => new Object({...card, suit: "Wands"}))
